---
title: "Implementasi Kebijakan Khusus"
editor: visual
---

## Implementasi Kebijakan Khusus

Sesuai dengan Peraturan Rektor UGM no 23 tahun 2024 tentang Pendidikan di lingkungan Universitas Gadjah Mada, terdapat jalur Program Pascasarjana berbasis penelitian pada PMPSTI. Jalur ini mengikuti Kurikulum PMPSTI-BR 2025. Bagi pelamar yang berasal dari lembaga/badan/institusi yang memiliki kerja sama dengan UGM, harus menyertakan kopi dokumen memorandum of understanding (MoU) atau perjanjian kerja sama dengan UGM atau surat penetapan sebagai penerima beasiswa. 

Untuk mendukung kesinambungan PSPSTIF dan PMPSTI, terdapat program percepatan program sarjana dan magister yang dapat ditempuh dalam waktu 5 tahun. Bagi pelamar yang merupakan mahasiswa program sarjana DTETI FT UGM harus memiliki minimal IPK 3,50 dengan masa studi sarjana maksimal 4 tahun dan telah memiliki proposal penelitian.

Syarat masuk untuk semua jalur di PMPSTI baik reguler ataupun berbasis riset mengikuti peraturan peraturan rektor yang berlaku. Kegiatan pembelajaran dalam PMPSTI megikuti Peraturan Rektor yang berlaku, dalam hal ini Peraturan Rektor UGM no 23 tahun 2024 yang meliputi metode luring, daring, dan bauran (blended learning).