---
title: "Persyaratan Kululusan (Yudisium)"
editor: visual
---

## Persyaratan Kelulusan (Yudisium)

Mahasiswa dinyatakan lulus untuk menyandang gelar Master of Engineering (M.Eng.) dalam bidang Teknologi Informasi bila telah memenuhi syarat-syarat sebagai berikut:

1.  IPK minimal 3,00 untuk regular dan 3,25 untuk yang berbasis penelitian.

2.  Telah menyelesaikan Tesis.

3.  Menerbitkan publikasi ilmiah atau diseminasi tugas akhir dalam bentuk lain sesuai aturan yang berlaku sesuai dengan syarat yang ditentukan pada masing-masing jalur  (berbasis perkuliahan atau penelitian). Authorship publikasi karya ilmiah harus sesuai dengan Peraturan Rektor nomor 23 tahun 2024.

4.  Telah lulus semua matakuliah sesuai struktur kurikulum.

5.  Telah memiliki kemampuan berbahasa Inggris yang dinyatakan dengan TOEFL score (Institutional Testing Program atau International) atau TOEFL-like score (paper base) 500. Dalam hal menggunakan TOEFL-like score maka ujian harus diselenggarakan di lingkungan Universitas Gadjah Mada.

6.  Telah menempuh masa studi paling singkat 3 (semester) semester dan paling lama 6 (enam) semester serta dapat diperpanjang sesuai aturan yang berlaku.