## Identitas Prodi

### Perguruan Tinggi

#### Nama {.unnumbered}
Universitas Gadjah Mada  

#### Visi {.unnumbered}
Sebagai pelopor perguruan tinggi nasional berkelas dunia yang unggul dan inovatif, mengabdi kepada kepentingan bangsa dan kemanusiaan, dijiwai nilai-nilai budaya bangsa berdasarkan Pancasila.

#### Misi {.unnumbered}

Melaksanakan pendidikan, penelitian, dan pengabdian kepada masyarakat serta pelestarian dan pengembangan ilmu yang unggul dan bermanfaat bagi masyarakat.



#### Tujuan {.unnumbered}

a.  Mewujudkan UGM sebagai lembaga nasional ilmu pengetahuan, kebudayaan, dan pendidikan tinggi yang menanamkan dan mengajarkan ilmu pengetahuan dan kebudayaan kepada Mahasiswa demi kelangsungan dan kehidupan manusia pada umumnya, demi perkembangan bangsa dan rakyat pada khususnya sebagai penjelmaan dan pelaksanaan Pancasila dan Undang-undang Dasar Negara Republik Indonesia Tahun 1945, serta demi tercapainya cita-cita Proklamasi Kemerdekaan sebagaimana ditentukan dalam Pembukaan Undang-undang Dasar Negara Republik Indonesia Tahun 1945;
b.  Membentuk manusia susila yang mempunyai keinsafan bertanggung jawab atas kesejahteraan Indonesia khususnya dan dunia umumnya, dalam arti berjiwa bangsa Indonesia, manusia budaya Indonesia, yang mempunyai dasar keinsafan hidup berketuhanan Yang Maha Esa, berperi kemanusiaan yang adil dan beradab, demokratis, diliputi oleh kenyataan dan kebenaran, cerdas, kreatif, terampil, mampu berkomunikasi dan berkesadaran lingkungan untuk melaksanakan tanggung jawabnya terhadap pembangunan, pemeliharaan dan pengembangan kebudayaan, hidup kemasyarakatan, serta masa depan bangsa dan negara Indonesia khususnya dan umat manusia pada umumnya.


### Fakultas {#sec-faculty}


#### Nama {.unnumbered}

Fakultas Teknik



#### Visi {.unnumbered}

Fakultas Teknik UGM menjadi lembaga pendidikan tinggi teknik berjejaring nasional dan global untuk penguatan peradaban baru, penguatan kemandirian dan kedaulatan bangsa di bidang IPTEK, dan perlambatan kenaikan entropi dunia, dalam rangka mengabdi kepada kepentingan bangsa dan kemanusiaan yang dijiwai oleh nilai-nilai budaya bangsa berdasarkan Pancasila



#### Misi {.unnumbered}

a.  Menyelenggarakan pendidikan untuk menghasilkan lulusan yang kompeten, berintegritas dan mampu menjadi pemimpin bangsa.
b.  Meningkatkan kegiatan penelitian dan pengabdian kepada masyarakat dalam rangka melestarikan, mengembangkan dan menghasilkan iptek yang berdampak pada kepentingan bangsa, kemanusiaan, peradaban dan perlambatan entropi dunia.
c.  Mengembangkan jejaring kerjasama multidisiplin dengan berbagai lembaga dalam dan luar negeri dalam rangka pengembangan tridarma perguruan tinggi.
d.  Meningkatkan tata kelola organisasi secara berkelanjutan yang berorientasi pada kepentingan manusia dalam konteks Society 5.0.



#### Tujuan {.unnumbered}

Menjadikan Fakultas Teknik UGM sebagai fakultas teknik terbaik di Indonesia dengan reputasi internasional melalui:

a.  Pendidikan tinggi teknik yang berkualitas dalam rangka menghasilkan lulusan yang unggul dan kompeten;

b.  Produk penelitian yang menjadi rujukan nasional yang berwawasan lingkungan dan responsif terhadap permasalahan masyarakat, bangsa, dan negara yang berbasis pada nilai-nilai keunggulan lokal;

c.  Pengabdian kepada masyarakat yang mampu mendorong kemandirian dan kesejahteraan masyarakat secara berkelanjutan;

d.  Tata kelola fakultas yang berkeadilan, transparan, partisipatif, akuntabel, dan terintegrasi antar bidang guna menunjang efektifitas dan efisiensi pemanfaatan sumber daya;

e.  Kerjasama yang strategis, sinergis, dan berkelanjutan dengan para mitra.


### Departemen


#### Nama {.unnumbered}

Departemen Teknik Elektro dan Teknologi Informasi



#### Visi {.unnumbered}

Departemen Teknik Elektro dan Teknologi Informasi menjadi sumber inovasi universal di bidang teknik elektro, informasi, dan biomedis untuk kepentingan bangsa dan kemanusiaan yang dijiwai nilai-nilai budaya bangsa berdasarkan Pancasila.



#### Misi {.unnumbered}

a.  Melaksanakan tridarma perguruan tinggi yang mampu menginternalisasi nilai-nilai DTETI (excellent, teamwork, harmony, optimistic, smart dan berintegritas: ETHOS for integrity) bagi kepentingan bangsa dan kemanusiaan.
b.  Mengembangkan lingkungan keilmuan yang mendorong tumbuhnya inovasi dalam pelaksanaan tridarma perguruan tinggi.



#### Tujuan {.unnumbered}

a.  Mewujudkan DTETI sebagai penyelenggara pendidikan di bidang teknik elektro, informasi, dan biomedis melalui program sarjana dan pascasarjana yang berkualitas, dalam rangka menghasilkan lulusan yang memiliki kompetensi tinggi, berkarakter dan berintegritas.
b.  Mengembangkan penelitian yang berkontribusi pada pengembangan keilmuan di bidang teknik elektro, informasi, dan biomedis untuk kepentingan bangsa Indonesia dan kemanusiaan secara universal.
c.  Menyelenggarakan pengabdian kepada masyarakat yang berkontribusi secara aktif dalam usaha penyelesaian berbagai masalah bangsa dan kemanusiaan secara universal melalui penyebaran dan penerapan produk-produk keilmuan di bidang teknik elektro, informasi, dan biomedis.
d.  Menjalin kerja sama yang strategis, sinergis, dan berkelanjutan dengan para mitra dalam rangka mendorong tumbuhnya keunggulan dan inovasi dalam pelaksanaan tridharma Perguruan Tinggi.
e.  Menegakkan tata pamong yang baik dalam penyelenggaraan tata kelola Departemen yang berkeadilan, transparan, partisipatif, akuntabel, dan terintegrasi antar bidang guna menunjang efektivitas dan efisiensi pemanfaatan sumber daya. Kerjasama yang strategis, sinergis, dan berkelanjutan dengan para mitra dalam rangka mendorong tumbuhnya keunggulan dan inovasi dalam pelaksanaan Tridharma.



#### Strategi Utama {.unnumbered}

a.  Penguatan orientasi keilmuan. DTETI akan berfokus pada pengembangan keilmuan berbasis keunggulan dan keunikan DTETI untuk peningkatan kemaslahatan masyarakat Indonesia dan Dunia melalui peningkatan kualitas pendidikan, penelitian, dan pengabdian kepada masyarakat (tri dharma) secara berkesinambungan.
b.  Penguatan kerjasama multiple-helix tingkat nasional dan internasional. Pengembangan jejaring mitra kerja sama strategis yang berkesinambungan untuk mendukung peningkatan kualitas tridharma.
c.  Penyelenggaraan tata pamong dan kelola yang lincah, fleksibel, tepat fungsi, dan tepat ukuran agar dapat secara cekatan, efektif, dan efisien menyesuaikan dengan tuntutan perubahan lingkungan. Tata pamong dan kelola yang baik akan meningkatkan kapasitas pengelolaan organisasi secara akuntabel, adil, transparan, efektif, dan efisien.


### Program Studi


#### Nama {.unnumbered}

Program Magister Program Studi Teknologi Informasi



#### Visi {.unnumbered}

Menjadi sumber inovasi yang universal di bidang ilmu Teknologi Informasi untuk kepentingan bangsa dan kemanusiaan dijiwai nilai-nilai bangsa berdasarkan Pancasila.



#### Misi {.unnumbered}

Melaksanakan Tridharma Perguruan Tinggi untuk mencetak lulusan yang cakap dan berintegritas dan menghasilkan penelitian yang dapat dimanfaatkan bagi kepentingan bangsa dan kemanusiaan.



#### Tujuan {.unnumbered}

Menjadikan Program Magister Program Studi Teknologi Informasi (PMPSTI) sebagai sumber inovasi dan keunggulan dalam bidang ilmu Teknologi Informasi melalui:

a.  Pengembangan pendidikan di bidang Teknologi Informasi yang berkualitas dalam rangka menghasilkan lulusan yang memiliki kompetensi tinggi, berkarakter, dan berintegritas,

b.  Pengembangan penelitian yang berkontribusi pada pengembangan keilmuan bidang Teknologi Informasi untuk kepentingan bangsa Indonesia dan kemanusiaan secara universal,

c.  Berkontribusi secara aktif dalam usaha penyelesaian masalah bangsa dan kemanusiaan secara universal melalui penyebaran dan penerapan produk-produk keilmuan dalam bidang Teknologi Informasi,

d.  Pengembangan lingkungan akademik yang mendorong tumbuhnya keunggulan dan inovasi dalam pelaksanaan Tridharma Perguruan Tinggi.


### Akreditasi

PMPSTI terakreditasi oleh BAN-PT dengan peringkat A untuk periode 22 Agustus 2017 sampai dengan 22 Agustus 2022. Kemudian mendapatkan akreditasi peringkat Unggul untuk periode 10 Mei 2022 sampai 5 Desember 2027.

a.  Jenjang Pendidikan

Jenjang pendidikan dari kurikulum ini adalah tingkat magister.

b.  Gelar Lulusan

Gelar lulusan yang akan diberikan adalah *Master of Engineering* (M.Eng.), sesuai dengan keputusan Rektor UGM nomor 292/P/SK/HT/2008 tentang gelar dan sebutan lulusan program pascasarjana (S2) Universitas Gadjah Mada.

c.  Profil Lulusan

Lulusan PMPSTI memiliki keahlian pada bidangnya dan cakap untuk melaksanakan penelitian dengan mengaplikasikan metode ilmiah untuk menyelesaikan masalah-masalah yang muncul sesuai dengan latar belakang keilmuan bidang teknologi informasi. Secara umum, lulusan PMPSTI dapat bekerja sebagai akademisi, peneliti, pegawai pemerintah, maupun profesional yang memiliki ciri kemampuan untuk analisis dan sintesis.