## Tujuan Pengajuan Kurikulum

Kurikulum ini diajukan guna mengakomodasi berbagai perubahan yang terjadi atas diterbitkannya Peraturan Menteri Pendidikan Tinggi, Sains, dan Teknologi No 39 tahun 2025 dan Peraturan Rektor No 23 tahun 2024 dan Peraturan Dekan FT UGM No. 1/2025. Penyelarasan terjadi atas alasan filosofis, sosiologis, psikologis, historis, hingga yuridis. Dasar-dasar aturan yang digunakan untuk menyesuaian antara lain KKNI dan SN-Dikti. Poin-poin perbaikan juga dipandu oleh analisis strength-weakness-opportunity-threat (SWOT). Semuanya akan bermuara pada aspek administratif yang tertuang dalam struktur perkuliahan, detail silabus, dan luaran pembelajaran yang diharapkan.

Beberapa perbedaan pokok dengan Kurikulum 2022 Versi Revisi-2 adalah, a) penyesuaian jumlah SKS menjadi 36 SKS berdasarkan Peraturan Menteri Pendidikan Tinggi, Sains, dan Teknologi No 39 Tahun 2025 tentang Penjaminan Mutu Pendidikan Tinggi, b) penambahan mata kuliah wajib umum berdasarkan Peraturan Dekan Fakultas Teknik UGM No. 1 Tahun 2025 tentang Pendidikan Program Pascasarjana, c) menjaga kesinambungan Program Studi Sarjana Teknologi Informasi, FT, UGM, d) pengembangan Kurikulum Program Magister Program Studi Teknologi Informasi Berbasis Penelitian (PMPSTI-BR) berdasarkan Peraturan Rektor UGM No. 23 Tahun 2024 tentang Pendidikan.